train:
  _target_: torch.utils.data.ConcatDataset # we can concat datasets if we want to
  datasets:
    - _target_: src.datasets.LibrispeechDataset
      part: "train_all"
      instance_transforms: ${transforms.instance_transforms.train}
    - _target_: src.datasets.CommonVoiceDataset
      split: "train"
      instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.LibrispeechDataset
  part: "test-clean"
  instance_transforms: ${transforms.instance_transforms.inference}
test:
  _target_: src.datasets.LibrispeechDataset
  part: "test-other"
  instance_transforms: ${transforms.instance_transforms.inference}
