train: [] # metrics that are calculated during training
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.ArgmaxCERMetric
    name: "CER_(Argmax)" # it is better to avoid spaces in names
  - _target_: src.metrics.ArgmaxWERMetric
    name: "WER_(Argmax)"
  - _target_: src.metrics.IdiotBeamSearchCERMetric
    name: "CER_(IdiotBeamSearch)"
  - _target_: src.metrics.IdiotBeamSearchWERMetric
    name: "WER_(IdiotBeamSearch)"
